/*****************************************************************************
 * Copyright (C) 2025 by Frederik Tobner                                     *
 *                                                                           *
 * This file is part of JANUS.                                              *
 *                                                                           *
 * Permission to use, copy, modify, and distribute this software and its     *
 * documentation under the terms of the GNU Affero General Public License is *
 * hereby granted.                                                           *
 * No representations are made about the suitability of this software for    *
 * any purpose.                                                              *
 * It is provided "as is" without express or implied warranty.               *
 * See the <https://www.gnu.org/licenses/agpl-3.0.en.html>                   *
 * GNU Affero General Public License                                         *
 * License for more details.                                                 *
 ****************************************************************************/

/**
 * @file version.h
 * @brief JANUS version information
 *
 * This header provides version-related macros and functions.
 * The actual version values come from config.h (generated by CMake).
 */

#ifndef JANUS_VERSION_H
#define JANUS_VERSION_H

#include <janus/config.h>

/**
 * Get the version string
 * @return Constant string with version information
 */
static inline char const * janus_version_string(void)
{
    return JANUS_VERSION_STRING;
}

/**
 * Get the full version string with build info
 * @return Constant string with full version information
 */
static inline char const * janus_full_version_string(void)
{
    return JANUS_FULL_VERSION_STRING;
}

/**
 * Get the project name
 * @return Constant string with project name
 */
static inline char const * janus_project_name(void)
{
    return JANUS_PROJECT_NAME;
}

#endif /* JANUS_VERSION_H */
