/**
 * @file version.h
 * @brief TinyOS version information
 * 
 * This header provides version-related macros and functions.
 * The actual version values come from config.h (generated by CMake).
 */

#ifndef TINYOS_VERSION_H
#define TINYOS_VERSION_H

#include <tinyos/config.h>

/**
 * Get the version string
 * @return Constant string with version information
 */
static inline const char* tinyos_version_string(void) {
    return TINYOS_VERSION_STRING;
}

/**
 * Get the full version string with build info
 * @return Constant string with full version information
 */
static inline const char* tinyos_full_version_string(void) {
    return TINYOS_FULL_VERSION_STRING;
}

/**
 * Get the project name
 * @return Constant string with project name
 */
static inline const char* tinyos_project_name(void) {
    return TINYOS_PROJECT_NAME;
}

/**
 * Check if version is at least the specified version
 * @param major Major version number
 * @param minor Minor version number
 * @param patch Patch version number
 * @return 1 if current version >= specified version, 0 otherwise
 */
static inline int tinyos_version_at_least(int major, int minor, int patch) {
    return TINYOS_VERSION_CODE >= TINYOS_VERSION_ENCODE(major, minor, patch);
}

#endif /* TINYOS_VERSION_H */
