/*****************************************************************************
 * Copyright (C) 2025 by Frederik Tobner                                     *
 *                                                                           *
 * This file is part of JANUS.                                               *
 *                                                                           *
 * Permission to use, copy, modify, and distribute this software and its     *
 * documentation under the terms of the GNU Affero General Public License is *
 * hereby granted.                                                           *
 * No representations are made about the suitability of this software for    *
 * any purpose.                                                              *
 * It is provided "as is" without express or implied warranty.               *
 * See the <https://www.gnu.org/licenses/agpl-3.0.en.html>                   *
 * GNU Affero General Public License                                         *
 * License for more details.                                                 *
 ****************************************************************************/

/**
 * @file codegen.c
 * @brief C header code generation for font data.
 */

#include "codegen.h"

#include <ctype.h>
#include <string.h>

void codegen_write_header(FILE * out, psf_font_t const * font, char const * prefix)
{
    char upper_prefix[64];
    size_t i;

    /* Create uppercase prefix for header guard */
    for (i = 0; i < sizeof(upper_prefix) - 1 && prefix[i]; i++) {
        upper_prefix[i] = toupper((unsigned char) prefix[i]);
    }
    upper_prefix[i] = '\0';

    /* File header comment */
    fprintf(out, "/**\n");
    fprintf(out, " * Auto-generated font data - do not edit\n");
    fprintf(out, " * Generated by psf2c\n");
    fprintf(out, " *\n");
    fprintf(out, " * Font: %ux%u pixels, %u glyphs\n", font->width, font->height, font->numglyphs);
    fprintf(out, " */\n\n");

    /* Header guard */
    fprintf(out, "#ifndef %s_H\n", upper_prefix);
    fprintf(out, "#define %s_H\n\n", upper_prefix);

    /* Include */
    fprintf(out, "#include <janus/types.h>\n\n");

    /* Macros */
    fprintf(out, "#define %s_WIDTH  %u\n", upper_prefix, font->width);
    fprintf(out, "#define %s_HEIGHT %u\n", upper_prefix, font->height);
    fprintf(out, "#define %s_GLYPH_COUNT %u\n", upper_prefix, font->numglyphs);
    fprintf(out, "#define %s_BYTES_PER_GLYPH %u\n\n", upper_prefix, font->bytesperglyph);

    /* Glyph data array */
    fprintf(out, "static const u8 %s_glyphs[%u][%u] = {\n", prefix, font->numglyphs, font->bytesperglyph);

    for (uint32_t g = 0; g < font->numglyphs; g++) {
        uint8_t const * glyph = font->glyphs + (g * font->bytesperglyph);

        /* Add comment for printable ASCII characters */
        if (g >= 0x20 && g <= 0x7E) {
            if (g == '\\' || g == '\'') {
                fprintf(out, "    /* 0x%02X '\\%c' */ { ", g, (char) g);
            } else {
                fprintf(out, "    /* 0x%02X '%c' */ { ", g, (char) g);
            }
        } else {
            fprintf(out, "    /* 0x%02X */ { ", g);
        }

        /* Write glyph bytes */
        for (uint32_t b = 0; b < font->bytesperglyph; b++) {
            fprintf(out, "0x%02X", glyph[b]);
            if (b < font->bytesperglyph - 1) {
                fprintf(out, ",");
            }
        }

        fprintf(out, " }");
        if (g < font->numglyphs - 1) {
            fprintf(out, ",");
        }
        fprintf(out, "\n");
    }

    fprintf(out, "};\n\n");
    fprintf(out, "#endif /* %s_H */\n", upper_prefix);
}
