/*****************************************************************************
 * Copyright (C) 2025 by Frederik Tobner                                     *
 *                                                                           *
 * This file is part of JANUS.                                               *
 *                                                                           *
 * Permission to use, copy, modify, and distribute this software and its     *
 * documentation under the terms of the GNU Affero General Public License is *
 * hereby granted.                                                           *
 * No representations are made about the suitability of this software for    *
 * any purpose.                                                              *
 * It is provided "as is" without express or implied warranty.               *
 * See the <https://www.gnu.org/licenses/agpl-3.0.en.html>                   *
 * GNU Affero General Public License                                         *
 * License for more details.                                                 *
 ****************************************************************************/

#include <ctype.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <zlib.h>

/* PSF1 constants */
#define PSF1_MAGIC0     0x36
#define PSF1_MAGIC1     0x04
#define PSF1_MODE512    0x01
#define PSF1_MODEHASTAB 0x02

/* PSF2 constants */
#define PSF2_MAGIC0     0x72
#define PSF2_MAGIC1     0xb5
#define PSF2_MAGIC2     0x4a
#define PSF2_MAGIC3     0x86

/* PSF1 header */
struct psf1_header {
    uint8_t magic[2];
    uint8_t mode;
    uint8_t charsize;
};

/* PSF2 header */
struct psf2_header {
    uint8_t magic[4];
    uint32_t version;
    uint32_t headersize;
    uint32_t flags;
    uint32_t numglyph;
    uint32_t bytesperglyph;
    uint32_t height;
    uint32_t width;
};

struct font_info {
    uint32_t width;
    uint32_t height;
    uint32_t numglyphs;
    uint32_t bytesperglyph;
    uint8_t * glyphs;
};

static void print_usage(char const * progname)
{
    fprintf(stderr, "Usage: %s <input.psf> <output.h> [symbol_prefix]\n", progname);
    fprintf(stderr, "\n");
    fprintf(stderr, "Convert a PSF font file to a C header.\n");
    fprintf(stderr, "Supports both raw .psf and gzip-compressed .psf.gz files.\n");
    fprintf(stderr, "\n");
    fprintf(stderr, "Arguments:\n");
    fprintf(stderr, "  input.psf      Input PSF font file (PSF1 or PSF2, optionally gzipped)\n");
    fprintf(stderr, "  output.h       Output C header file\n");
    fprintf(stderr, "  symbol_prefix  Optional prefix for symbols (default: font)\n");
}

static void write_header(FILE * out, const struct font_info * info, char const * prefix)
{
    char upper_prefix[64];
    size_t i;

    /* Create uppercase prefix for header guard */
    for (i = 0; i < sizeof(upper_prefix) - 1 && prefix[i]; i++) {
        upper_prefix[i] = toupper((unsigned char) prefix[i]);
    }
    upper_prefix[i] = '\0';

    fprintf(out, "/**\n");
    fprintf(out, " * Auto-generated font data - do not edit\n");
    fprintf(out, " * Generated by psf2c\n");
    fprintf(out, " *\n");
    fprintf(out, " * Font: %ux%u pixels, %u glyphs\n", info->width, info->height, info->numglyphs);
    fprintf(out, " */\n\n");

    fprintf(out, "#ifndef %s_H\n", upper_prefix);
    fprintf(out, "#define %s_H\n\n", upper_prefix);

    fprintf(out, "#include <janus/types.h>\n\n");

    fprintf(out, "#define %s_WIDTH  %u\n", upper_prefix, info->width);
    fprintf(out, "#define %s_HEIGHT %u\n", upper_prefix, info->height);
    fprintf(out, "#define %s_GLYPH_COUNT %u\n", upper_prefix, info->numglyphs);
    fprintf(out, "#define %s_BYTES_PER_GLYPH %u\n\n", upper_prefix, info->bytesperglyph);

    fprintf(out, "static const u8 %s_glyphs[%u][%u] = {\n", prefix, info->numglyphs, info->bytesperglyph);

    for (uint32_t g = 0; g < info->numglyphs; g++) {
        uint8_t const * glyph = info->glyphs + (g * info->bytesperglyph);

        /* Add comment for printable ASCII characters */
        if (g >= 0x20 && g <= 0x7E) {
            if (g == '\\' || g == '\'') {
                fprintf(out, "    /* 0x%02X '\\%c' */ { ", g, (char) g);
            } else {
                fprintf(out, "    /* 0x%02X '%c' */ { ", g, (char) g);
            }
        } else {
            fprintf(out, "    /* 0x%02X */ { ", g);
        }

        for (uint32_t b = 0; b < info->bytesperglyph; b++) {
            fprintf(out, "0x%02X", glyph[b]);
            if (b < info->bytesperglyph - 1) {
                fprintf(out, ",");
            }
        }

        fprintf(out, " }");
        if (g < info->numglyphs - 1) {
            fprintf(out, ",");
        }
        fprintf(out, "\n");
    }

    fprintf(out, "};\n\n");
    fprintf(out, "#endif /* %s_H */\n", upper_prefix);
}

/* Gzip magic bytes */
#define GZIP_MAGIC0 0x1f
#define GZIP_MAGIC1 0x8b

static int is_gzip(const char * path)
{
    FILE * fp = fopen(path, "rb");
    if (!fp) {
        return 0;
    }

    uint8_t magic[2];
    int is_gz = (fread(magic, 1, 2, fp) == 2 && magic[0] == GZIP_MAGIC0 && magic[1] == GZIP_MAGIC1);
    fclose(fp);
    return is_gz;
}

static int read_psf_from_buffer(uint8_t const * data, size_t size, struct font_info * info)
{
    /* Check for PSF2 */
    if (size >= 4 && data[0] == PSF2_MAGIC0 && data[1] == PSF2_MAGIC1 && data[2] == PSF2_MAGIC2 &&
        data[3] == PSF2_MAGIC3) {

        if (size < sizeof(struct psf2_header)) {
            fprintf(stderr, "Error: File too small for PSF2 header\n");
            return -1;
        }

        const struct psf2_header * hdr = (const struct psf2_header *) data;
        printf("Detected PSF2 format\n");

        info->width = hdr->width;
        info->height = hdr->height;
        info->numglyphs = hdr->numglyph;
        info->bytesperglyph = hdr->bytesperglyph;

        size_t data_size = hdr->numglyph * hdr->bytesperglyph;
        if (hdr->headersize + data_size > size) {
            fprintf(stderr, "Error: File too small for glyph data\n");
            return -1;
        }

        info->glyphs = malloc(data_size);
        if (!info->glyphs) {
            fprintf(stderr, "Error: Out of memory\n");
            return -1;
        }
        memcpy(info->glyphs, data + hdr->headersize, data_size);
        return 0;
    }

    /* Check for PSF1 */
    if (size >= 2 && data[0] == PSF1_MAGIC0 && data[1] == PSF1_MAGIC1) {
        if (size < sizeof(struct psf1_header)) {
            fprintf(stderr, "Error: File too small for PSF1 header\n");
            return -1;
        }

        const struct psf1_header * hdr = (const struct psf1_header *) data;
        printf("Detected PSF1 format\n");

        size_t glyph_count = (hdr->mode & PSF1_MODE512) ? 512 : 256;

        info->width = 8;
        info->height = hdr->charsize;
        info->numglyphs = glyph_count;
        info->bytesperglyph = hdr->charsize;

        size_t data_size = glyph_count * hdr->charsize;
        if (sizeof(struct psf1_header) + data_size > size) {
            fprintf(stderr, "Error: File too small for glyph data\n");
            return -1;
        }

        info->glyphs = malloc(data_size);
        if (!info->glyphs) {
            fprintf(stderr, "Error: Out of memory\n");
            return -1;
        }
        memcpy(info->glyphs, data + sizeof(struct psf1_header), data_size);
        return 0;
    }

    fprintf(stderr,
            "Error: Unknown file format (magic: %02x %02x %02x %02x)\n",
            data[0],
            data[1],
            size > 2 ? data[2] : 0,
            size > 3 ? data[3] : 0);
    return -1;
}

static int load_gzip_file(char const * path, uint8_t ** out_data, size_t * out_size)
{
    gzFile gz = gzopen(path, "rb");
    if (!gz) {
        fprintf(stderr, "Error: Cannot open gzip file '%s'\n", path);
        return -1;
    }

    printf("Decompressing gzip file...\n");

    size_t capacity = 64 * 1024; /* Start with 64KB */
    size_t size = 0;
    uint8_t * data = malloc(capacity);
    if (!data) {
        gzclose(gz);
        fprintf(stderr, "Error: Out of memory\n");
        return -1;
    }

    int bytes_read;
    while ((bytes_read = gzread(gz, data + size, capacity - size)) > 0) {
        size += bytes_read;
        if (size == capacity) {
            capacity *= 2;
            uint8_t * new_data = realloc(data, capacity);
            if (!new_data) {
                free(data);
                gzclose(gz);
                fprintf(stderr, "Error: Out of memory\n");
                return -1;
            }
            data = new_data;
        }
    }

    if (bytes_read < 0) {
        int errnum;
        char const * errmsg = gzerror(gz, &errnum);
        fprintf(stderr, "Error: Failed to decompress: %s\n", errmsg);
        free(data);
        gzclose(gz);
        return -1;
    }

    gzclose(gz);
    *out_data = data;
    *out_size = size;
    return 0;
}

static int load_regular_file(char const * path, uint8_t ** out_data, size_t * out_size)
{
    FILE * fp = fopen(path, "rb");
    if (!fp) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", path);
        return -1;
    }

    fseek(fp, 0, SEEK_END);
    long file_size = ftell(fp);
    fseek(fp, 0, SEEK_SET);

    if (file_size <= 0) {
        fprintf(stderr, "Error: Empty or invalid file\n");
        fclose(fp);
        return -1;
    }

    uint8_t * data = malloc(file_size);
    if (!data) {
        fprintf(stderr, "Error: Out of memory\n");
        fclose(fp);
        return -1;
    }

    if (fread(data, 1, file_size, fp) != (size_t) file_size) {
        fprintf(stderr, "Error: Failed to read file\n");
        free(data);
        fclose(fp);
        return -1;
    }

    fclose(fp);
    *out_data = data;
    *out_size = file_size;
    return 0;
}

int main(int argc, char * argv[])
{
    char const * input_path;
    char const * output_path;
    char const * prefix;
    FILE * fp_out;
    struct font_info info = {0};
    uint8_t * file_data = NULL;
    size_t file_size = 0;
    int ret = 1;

    if (argc < 3) {
        print_usage(argv[0]);
        return 1;
    }

    input_path = argv[1];
    output_path = argv[2];
    prefix = (argc >= 4) ? argv[3] : "font";

    /* Load file (with automatic gzip detection) */
    if (is_gzip(input_path)) {
        if (load_gzip_file(input_path, &file_data, &file_size) != 0) {
            return 1;
        }
    } else {
        if (load_regular_file(input_path, &file_data, &file_size) != 0) {
            return 1;
        }
    }

    /* Parse PSF data */
    if (read_psf_from_buffer(file_data, file_size, &info) != 0) {
        free(file_data);
        return 1;
    }

    free(file_data);

    printf(
        "Font info: %ux%u, %u glyphs, %u bytes/glyph\n", info.width, info.height, info.numglyphs, info.bytesperglyph);

    fp_out = fopen(output_path, "w");
    if (!fp_out) {
        fprintf(stderr, "Error: Cannot open output file '%s'\n", output_path);
        free(info.glyphs);
        return 1;
    }

    write_header(fp_out, &info, prefix);
    fclose(fp_out);

    printf("Generated: %s\n", output_path);
    ret = 0;

    free(info.glyphs);
    return ret;
}
